apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  ports:
  - name: platformservice
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: platform
  type: ClusterIP
